# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_butt_wid.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_us_wid(object):
    def setupUi(self, us_wid):
        us_wid.setObjectName("us_wid")
        us_wid.resize(148, 70)
        self.open_chat_with_us_butt = QtWidgets.QPushButton(us_wid)
        self.open_chat_with_us_butt.setGeometry(QtCore.QRect(0, 0, 148, 70))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.open_chat_with_us_butt.setFont(font)
        self.open_chat_with_us_butt.setObjectName("open_chat_with_us_butt")
        self.status_us = QtWidgets.QGraphicsView(us_wid)
        self.status_us.setGeometry(QtCore.QRect(0, 0, 10, 10))
        self.status_us.setObjectName("status_us")

        self.retranslateUi(us_wid)
        QtCore.QMetaObject.connectSlotsByName(us_wid)

    def retranslateUi(self, us_wid):
        _translate = QtCore.QCoreApplication.translate
        us_wid.setWindowTitle(_translate("us_wid", "Form"))
        self.open_chat_with_us_butt.setText(_translate("us_wid", "Name_user"))
